# Generated by Django 3.1.3 on 2020-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thr_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('thr_title', models.CharField(max_length=100)),
                ('thr_content', models.TextField()),
                ('thr_keywords', models.JSONField()),
                ('thr_postdate', models.DateField()),
                ('thr_upvotes', models.IntegerField()),
                ('thr_downvotes', models.IntegerField()),
                ('thr_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('thr_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'db_table': 'thread',
            },
        ),
    ]
