# Generated by Django 3.1.3 on 2020-11-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thr_author',
            field=models.ForeignKey(db_column='usr_id', on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='users.user'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thr_category',
            field=models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.category'),
        ),
    ]
