# Generated by Django 3.1.3 on 2020-11-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('threads', '0002_auto_20201115_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thr_author',
        ),
        migrations.AlterField(
            model_name='thread',
            name='thr_category',
            field=models.ForeignKey(db_column='thr_category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.category'),
        ),
    ]
