# Generated by Django 3.1.3 on 2020-11-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20201115_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thr_author',
        ),
    ]
