# Generated by Django 3.1.3 on 2020-11-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_remove_thread_thr_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thr_category',
        ),
    ]
