# Generated by Django 3.1.3 on 2020-11-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20201115_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thr_author',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='thr_keywords',
        ),
    ]
