# Generated by Django 3.1.3 on 2020-11-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('threads', '0008_auto_20201115_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thr_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user', verbose_name='Author'),
        ),
    ]
