# Generated by Django 3.1.3 on 2020-11-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('threads', '0010_remove_thread_thr_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thr_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.category'),
        ),
    ]
