# Generated by Django 3.1.3 on 2020-11-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
        ('threads', '0011_auto_20201115_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thr_author',
            field=models.ForeignKey(db_column='thr_author', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thr_category',
            field=models.ForeignKey(db_column='thr_category', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.category'),
        ),
    ]
