# Generated by Django 3.1.3 on 2020-11-18 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20201115_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thr_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thr_postdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thr_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
