# Generated by Django 3.1.3 on 2020-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0013_auto_20201118_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
