# Generated by Django 3.1.3 on 2020-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=18)),
                ('usr_password', models.TextField()),
                ('usr_registrationdate', models.DateField()),
                ('usr_totalupvotes', models.IntegerField()),
                ('usr_totaldownvotes', models.IntegerField()),
            ],
            options={
                'db_table': 'usr',
            },
        ),
    ]
