# Generated by Django 3.1.3 on 2020-11-17 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_registrationdate',
            field=models.DateField(default=models.DateField(default=django.utils.timezone.now, editable=False)),
        ),
        migrations.AlterField(
            model_name='user',
            name='usr_totaldownvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='usr_totalupvotes',
            field=models.IntegerField(default=0),
        ),
    ]
