# Generated by Django 3.1.3 on 2020-11-17 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201117_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='usr_password',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='usr_registrationdate',
            field=models.DateTimeField(default=models.DateField(default=django.utils.timezone.now, editable=False)),
        ),
    ]
