# Generated by Django 3.1.3 on 2020-11-17 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201117_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_registrationdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
