# Generated by Django 3.1.3 on 2020-11-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201117_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_password',
            field=models.TextField(),
        ),
    ]
