# Generated by Django 3.1.3 on 2020-11-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201117_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usr_password',
        ),
    ]
