# Generated by Django 3.1.3 on 2020-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('com_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('com_text', models.CharField(max_length=1000)),
                ('com_postdate', models.DateField()),
                ('com_upvotes', models.IntegerField()),
                ('com_downvotes', models.IntegerField()),
                ('com_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('com_thrlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
