# Generated by Django 3.1.3 on 2020-11-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
        ('users', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_author',
            field=models.ForeignKey(db_column='usr_id', on_delete=django.db.models.deletion.CASCADE, related_name='usr', to='users.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_thrlocation',
            field=models.ForeignKey(db_column='thr_id', on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='threads.thread'),
        ),
    ]
