# Generated by Django 3.1.3 on 2020-11-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('threads', '0003_auto_20201115_1456'),
        ('comments', '0002_auto_20201115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_thrlocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='threads.thread', verbose_name='Thread location'),
        ),
    ]
