# Generated by Django 3.1.3 on 2020-11-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_remove_thread_thr_category'),
        ('users', '0001_initial'),
        ('comments', '0004_auto_20201115_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_thrlocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='threads.thread', verbose_name='Thread location'),
        ),
    ]
