# Generated by Django 3.1.3 on 2020-11-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20201115_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com_author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='com_thrlocation',
        ),
    ]
