# Generated by Django 3.1.3 on 2020-11-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20201115_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com_author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='com_thrlocation',
        ),
    ]
