# Generated by Django 3.1.3 on 2020-11-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('threads', '0011_auto_20201115_1532'),
        ('comments', '0008_auto_20201115_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_author',
            field=models.ForeignKey(db_column='com_author', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_thrlocation',
            field=models.ForeignKey(db_column='com_thrlocation', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='threads.thread'),
        ),
    ]
